### ISSUE TITLE
Error: Cannot find module '../models/user'

### ISSUE THREAD

**Issue by rohan-paul** [didinj/mern-stack-authentication#2]
After running ``npm start`` was gettng the below error

```
Error: Cannot find module '../models/user'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/paul/PAUL/H/Web/R/R-Vid/WIP/Authentication-Signup-jwt/MERN-Blog/mern-stack-authentication/config/passport.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/paul/PAUL/H/Web/R/R-Vid/WIP/Authentication-Signup-jwt/MERN-Blog/mern-stack-authentication/routes/book.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)

```

**Comment by rohan-paul** [comment]
Fixed it - In /config/passport.js and routes/auth.js changed the below line as below

```
var User = require("../models/User");
```

Now its working

**Comment by jehovahcreations** [comment]
Check this, briefly explained here, and you can fix it https://youtu.be/idJHHxA02l8
