### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by lmilliken** [didinj/mern-stack-authentication#4]
I cloned the repo and go this error when going to http://localhost:3000, any thoughts?

```
Error: No default engine was specified and no extension was provided.
    at new View (...mern-stack-authentication\node_modules\express\lib\view.js:61:11)
    at Function.render (...mern-stack-authentication\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (...mern-stack-authentication\node_modules\express\lib\response.js:1008:7)
    at ...mern-stack-authentication\app.js:40:7
    at Layer.handle_error (...mern-stack-authentication\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (...mern-stack-authentication\node_modules\express\lib\router\index.js:315:13)
    at ...mern-stack-authentication\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (...mern-stack-authentication\node_modules\express\lib\router\index.js:335:12)
    at next (...mern-stack-authentication\node_modules\express\lib\router\index.js:275:10)
    at ...mern-stack-authentication\app.js:29:3
    at Layer.handle [as handle_request] (...mern-stack-authentication\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (...mern-stack-authentication\node_modules\express\lib\router\index.js:317:13)
    at ...mern-stack-authentication\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (...mern-stack-authentication\node_modules\express\lib\router\index.js:335:12)
    at next (...mern-stack-authentication\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (...mern-stack-authentication\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (events.js:182:13)
    at SendStream.error (...mern-stack-authentication\node_modules\send\index.js:270:17)
    at SendStream.onStatError (...mern-stack-authentication\node_modules\send\index.js:421:12)
    at next (...mern-stack-authentication\node_modules\send\index.js:764:28)
    at ...mern-stack-authentication\node_modules\send\index.js:772:23
    at FSReqWrap.oncomplete (fs.js:158:21)
```

**Comment by lmilliken** [comment]
nevermind, rtfd :)
